Add a way to iterate over cetificates in store
google/certtostore pull request #72
Opened 2024-05-03 13:51 UTC by harture

2024-05-20 19:25 UTC, mit-da requested changes
Line 71, the CertWithContext() in the WinCertStorage interface needs to be updated for this change.

2024-05-20 19:25 UTC, mit-da commented
Looks like you also have to sign the CLA.

2025-02-11 18:41 UTC, mit-da commented
Do you still want to push this change forward @harture?

2025-06-12 22:19 UTC, alexherrero commented
Closing due to inactivity, please re-open if you'd still like to merge this request.

2025-06-12 22:19 UTC, closed without merging